version: "3"

services:
  frontend:
    build: ./frontend
    image: lavax-frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backend-network

  backend:
    build: ./backend
    image: lavax-backend
    restart: always
    hostname: nestjs
    ports:
      - "3002:3002"
    env_file:
      - ./backend/.env
    networks:
      - backend-network
    links:
      - postgres_db
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:13
    env_file:
      - ./backend/.env
    container_name: postgres_container
    hostname: ${POSTGRES_HOSTNAME}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres_db
    env_file:
      - ./backend/.env
    ports:
      - "5555:80"
    networks:
      - backend-network
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    name: infra
