version: '3'

services:
  postgres_db_dev:
    image: postgres:13
    env_file:
      - .env
    container_name: postgres_container1
    hostname: ${POSTGRES_HOSTNAME}
    ports:
      - '6543:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin_dev:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    depends_on:
      - postgres_db_dev
    env_file:
      - .env
    ports:
      - '5556:80'
    networks:
      - backend-network
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
  frontend-network:
    name: infra
